### ISSUE TITLE
cuda10.2 and 3060 do not match

### ISSUE THREAD

**Issue by Richard-mei** [researchmm/Stark#23]
###  cuda10.2:
```
NVIDIA GeForce RTX 3060 Laptop GPU with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3060 Laptop GPU GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
```

###  cuda11.0:
```
WARNING: You are using tensorboardX instead sis you have a too old pytorch version.
Traceback (most recent call last):
  File "tracking/../lib/train/admin/tensorboard.py", line 4, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/torch/lib/../../../../libcublas.so.11: symbol free_gemm_select version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tracking/video_demo.py", line 9, in <module>
    from lib.test.evaluation import Tracker
  File "tracking/../lib/test/evaluation/__init__.py", line 1, in <module>
    from .data import Sequence
  File "tracking/../lib/test/evaluation/data.py", line 3, in <module>
    from lib.train.data.image_loader import imread_indexed
  File "tracking/../lib/train/__init__.py", line 1, in <module>
    from .admin.multigpu import MultiGPU
  File "tracking/../lib/train/admin/__init__.py", line 3, in <module>
    from .tensorboard import TensorboardWriter
  File "tracking/../lib/train/admin/tensorboard.py", line 7, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
```

###  but when i installed tensorboardX:
```
WARNING: You are using tensorboardX instead sis you have a too old pytorch version.
Traceback (most recent call last):
  File "tracking/../lib/train/admin/tensorboard.py", line 4, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/torch/lib/../../../../libcublas.so.11: symbol free_gemm_select version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tracking/video_demo.py", line 9, in <module>
    from lib.test.evaluation import Tracker
  File "tracking/../lib/test/evaluation/__init__.py", line 1, in <module>
    from .data import Sequence
  File "tracking/../lib/test/evaluation/data.py", line 3, in <module>
    from lib.train.data.image_loader import imread_indexed
  File "tracking/../lib/train/__init__.py", line 1, in <module>
    from .admin.multigpu import MultiGPU
  File "tracking/../lib/train/admin/__init__.py", line 3, in <module>
    from .tensorboard import TensorboardWriter
  File "tracking/../lib/train/admin/tensorboard.py", line 7, in <module>
    from tensorboardX import SummaryWriter
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/tensorboardX/__init__.py", line 5, in <module>
    from .torchvis import TorchVis
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/tensorboardX/torchvis.py", line 11, in <module>
    from .writer import SummaryWriter
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/tensorboardX/writer.py", line 34, in <module>
    import torch
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/torch/__init__.py", line 189, in <module>
    _load_global_deps()
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/torch/__init__.py", line 142, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/richard/miniconda3/envs/torch1.7/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/richard/miniconda3/envs/torch1.7/lib/python3.6/site-packages/torch/lib/../../../../libcublas.so.11: symbol free_gemm_select version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference
```

**Comment by MasterBin-IIAU** [comment]
@Richard-mei Hi, I think the CUDA version doesn't have an influence on this project. So you can choose the compatible CUDA and the PyTorch version based on your GPU. For example, you can create a new conda environment then run the install_pytorch17.sh but replace the original command ```conda install -y pytorch==1.7.0 torchvision==0.8.1 cudatoolkit=10.2 -c pytorch``` with ```conda install pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=11.0 -c pytorch```.

**Comment by Richard-mei** [comment]
I have tried ```pytorch==1.7.0 torchvision==0.8.1 torchaudio==0.7.0 cudatoolkit=11.0```, but as I said above, an error about tensorboardX occured.

**Comment by MasterBin-IIAU** [comment]
We haven't tested our code on a 3060 GPU. However, if you only want to run demos or test the STARK tracker, you can just comment out all lines about tensorboard.

**Comment by Richard-mei** [comment]
Thank you. I replaced with ```conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge``` and it works.
